### ISSUE TITLE
Class with a non-mapped property

### ISSUE THREAD

**Issue by ani2479** [zzzprojects/System.Linq.Dynamic.Core#271]
Hi,

If I have a class that has a property non mapped, how can I do a Where?

I tried `entity.Where(c=>c.navigation.nonmappedporperty.Contains("ovi"));` and works, but if I try `entity.Where("np(navigation.nonmappedproperty).contains(\"ovi\")")` I get 

```
Microsoft.EntityFrameworkCore.Query:Error: An exception occurred in the database while iterating the results of a query for context type 
System.NullReferenceException: Object reference not set to an instance of an object.
   at lambda_method(Closure , TransparentIdentifier`2 )
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider._TrackEntities[TOut,TIn](IEnumerable`1 results, QueryContext queryContext, IList`1 entityTrackingInfos, IList`1 entityAccessors)+MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
```

The OrderBy gets the following error:
Value cannot be null.
Parameter name: source

Any ideas?

Thanks again

**Comment by ani2479** [comment]
Or is it a way to do an any?

Like entity.Where(c => c.navigation.Any(d => d.property == 1))?

**Comment by StefH** [comment]
Maybe this code will work:

``` c#
entity.Where("navigation.nonmappedproperty != null ? navigation.nonmappedproperty.contains(\"ovi\") : false")
```

**Comment by ani2479** [comment]
Hi, I got the same error. But I think is because EF core is not able to check that property
Value cannot be null.
Parameter name: source

**Comment by StefH** [comment]
Can you please provide a full example project or https://dotnetfiddle.net/ ?

**Comment by JonathanMagnan** [comment]
Hello @ani2479 ,

This issue will be closed since I believe no project or fiddle has been provided.

If you can reproduce it in a standalone project, we will be happy to re-open and investigate it.

Best Regards,
 
Jon
 
---
 
**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)
 
**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)
