### ISSUE TITLE
SumAsync and CountAsync (maybe more) do not work with EF Core 3.1

### ISSUE THREAD

**Issue by wertzui** [zzzprojects/System.Linq.Dynamic.Core#391]
Using these methods triggers a MethodNotFoundException on EF Core 3.1.
From what I've seen, this library still references EF Core 2.2 so this might be the problem.

This should also be supported on netcore2.1 which will only require a minimal change, because `TypeInfo` is gone, so there is no `AsType()` method on it. Instead `GenericTypeParameterBuilder` directly inherits `Type`.

**Comment by JonathanMagnan** [comment]
Hello @wertzui ,

Thank you for reporting.

In fact, the library reference EF Core 1.1

Before doing this request, we will need to discuss in a new thread about how people would like we manage this library (we cannot simply upgrade the reference, otherwise people using v2.x will no longer be able to use it).

I should create an issue about this in the coming weeks. So this issue will not be fixed this month but that's definitely something we will look and try to complete during the summer.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by StefH** [comment]
@JonathanMagnan 

I had the same issue for LinqKit, see this link for my solution:
https://github.com/scottksmith95/LINQKit/blob/master/README.md#projects

I think the same logic can be applied for `Microsoft.EntityFrameworkCore.DynamicLinq`.

**Comment by JonathanMagnan** [comment]
Yup @StefH ,

Using the major version to be the same as the `EF Core` version is the solution that we will probably take as well (Also the solution we already implemented for EFE and EF Plus).

**Comment by JonathanMagnan** [comment]
Hello @wertzui ,

Sorry for the long delay,

The v3.2.0 has been released: https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.DynamicLinq/3.2.0

Starting from this version, the library should now be compatible with EF Core 3.1 or greater.

Best Regards,

Jon
