### ISSUE TITLE
[Question] OrderBy does not work with nullable navigation properties 

### ISSUE THREAD

**Issue by khallid-itdevtech** [zzzprojects/System.Linq.Dynamic.Core#400]
OrderBy  works fine on non nullable navigation properties but if navigation property is nullable it doesn't work

System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseArgumentList() in ExpressionParser.cs, line 1851

 list = list.AsQueryable().OrderBy("site.title  asc" ).ToList();

site is nullable navigation property

**Comment by JonathanMagnan** [comment]
Hello @khallid-itdevtech ,

Do you think you could provide a project sample with this issue?

It will help my developer investigate the issue more efficiently.

We already tried once but everything was working, so we might miss something.

_We now always ask for a project sample even if the issue is easy to reproduce. As a free product, we must find some way to save time to offer an overall better experience for everyone and release fixes faster._

_You can send it to: info@zzzprojects.com if you need to keep the source private_

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by StefH** [comment]
I think the **site** is a nullable navigation property in this question. So you cannot use `site.title asc` because site is null.

The solution is to use the NullPropagating (np) function, so I think this code should solve the issue
``` c#
list = list.AsQueryable().OrderBy("np(site.title) asc" ).ToList();
```

**Comment by JonathanMagnan** [comment]
I was getting a different error when the `site` was null (Null reference exception which is was I'm expecting).

I guess we will see with his answer ;)

**Comment by khallid-itdevtech** [comment]
@StefH Thanks
list = list.AsQueryable().OrderBy("np(site.title) asc" ).ToList();
this works like charm.  👍
