### ISSUE TITLE
'Methods on type 'MyClass' are not accessible'

### ISSUE THREAD

**Issue by nowire** [zzzprojects/System.Linq.Dynamic.Core#689]
Dear,

With the old version (1.2.25) of the library I could call methods of the class in the order function. With the new version I get an error that the method is not accessible.

``` c#
IEnumerable<PilotWithCO> pilotwithcolist = pilotwithcolist.AsQueryable().Where(where).OrderBy(order).ToList();
```

in order string I have, for example: "`PenaltyTotal ascending, GetCOPenalty(0,2) ascending, GetCOPenalty(0,3) ascending`"

where `GetCOPenalty(0,2)` is a public method of PilotWithCO class

System.Linq.Dynamic.Core.Exceptions.ParseException: 'Methods on type 'PilotWithCO' are not accessible'

**Comment by piotrroda** [comment]
I have the same exception after bumping to 1.3.1 version
`System.Linq.Dynamic.Core.Exceptions.ParseException : Methods on type 'IInnerSlsRoleProxy' are not accessible`

**Comment by StefH** [comment]
## Breaking changes

### v1.3.0
A breaking change is introduced in version 1.3.0 which is related to calling methods on classes.
Due to security reasons, it's now only allowed to call methods on the standard predefined classes like (`bool`, `int`, `string` ...).
If you want to call a method on an own custom class, annotate that class with the [DynamicLinqType](https://dynamic-linq.net/advanced-extending#dynamiclinqtype-attribute).
Example:
``` c#
[DynamicLinqType]
public class MyCustomClass
{
    public int GetAge(int x) => x;
}
```

If it's not possible to add that attribute, you need to implement a custom [CustomTypeProvider](https://dynamic-linq.net/advanced-configuration#customtypeprovider) and set this to the `ParsingConfig` and provide that config to the dynamic call.
