### ISSUE TITLE
Performance Issue with EF Core 8.0 and Microsoft.EntityFrameworkCore.DynamicLinq Package

### ISSUE THREAD

**Issue by codepassion86** [zzzprojects/System.Linq.Dynamic.Core#783]
## 1. Description
Hello @StefH 

I am reaching out to you to report a performance issue encountered with version 8.0 of EF Core, specifically concerning the "Microsoft.EntityFrameworkCore.DynamicLinq ver. 8.3.10" package.

We have observed significant slowdowns (over a minute of waiting) when executing an order by on any query, even when dealing with a minimal number of results (even with just one record). This slowdown occurs only during the initial execution.

We would appreciate any guidance on how to resolve this issue or if there are any updates or alternative solutions available to improve the performance of this package.

Thank you in advance for your attention and assistance regarding this matter.

Best regards.

**Comment by StefH** [comment]
Related #781

**Comment by codepassion86** [comment]
Ok, but with the .NET 6.0 version this problem did not appear

**Comment by StefH** [comment]
I did create an example project which uses MS SQL. And tested 6 and 8, not much difference:

(The first query is indeed slower)

## .NET 6 (Release mode)
```
Elapsed time: 1393,0677ms
1, Star Wars Episode IV: A New Hope, 1979, 10
2, Ghostbusters, 1984, 5,5
3, Terminator, 1984, 8,5
4, Taxi Driver, 1976, 5
8, Analyze This, 1999, 10,5
9, Leon: the Professional, 1994, 8,5
10, Mission Impossible, 1996, 8,5
--------------------------------------------------------------------------------
Elapsed time: 4,9237ms
1, Star Wars Episode IV: A New Hope, 1979, 10
2, Ghostbusters, 1984, 5,5
3, Terminator, 1984, 8,5
4, Taxi Driver, 1976, 5
8, Analyze This, 1999, 10,5
9, Leon: the Professional, 1994, 8,5
10, Mission Impossible, 1996, 8,5
```

## .NET 8 (Release mode)
```
Elapsed time: 1063,9211ms
1, Star Wars Episode IV: A New Hope, 1979, 10
2, Ghostbusters, 1984, 5,5
3, Terminator, 1984, 8,5
4, Taxi Driver, 1976, 5
8, Analyze This, 1999, 10,5
9, Leon: the Professional, 1994, 8,5
10, Mission Impossible, 1996, 8,5
--------------------------------------------------------------------------------
Elapsed time: 5,7117ms
1, Star Wars Episode IV: A New Hope, 1979, 10
2, Ghostbusters, 1984, 5,5
3, Terminator, 1984, 8,5
4, Taxi Driver, 1976, 5
8, Analyze This, 1999, 10,5
9, Leon: the Professional, 1994, 8,5
10, Mission Impossible, 1996, 8,5
```

See this PR for details
https://github.com/zzzprojects/System.Linq.Dynamic.Core/pull/785

**Comment by StefH** [comment]
@codepassion86 
The default implementation from the [DefaultDynamicLinqCustomTypeProvider.cs](https://github.com/zzzprojects/System.Linq.Dynamic.Core/blob/master/src/System.Linq.Dynamic.Core/CustomTypeProviders/DefaultDynamicLinqCustomTypeProvider.cs) is to load all assemblies to search for DynamicLinq types. In case your solution does include a lot of dependencies/assemblies, all these need to be scanned.

In order to limit this, you can build your own provider which implements [IDynamicLinqCustomTypeProvider.cs](https://github.com/zzzprojects/System.Linq.Dynamic.Core/blob/master/src/System.Linq.Dynamic.Core/CustomTypeProviders/IDynamicLinqCustomTypeProvider.cs) where you only load the assemblies which are required for your application.

**Comment by StefH** [comment]
@codepassion86 
Did you have time yet to validate this?

**Comment by StefH** [comment]
Closing this in favor of #790
